# Generated by Django 2.1.7 on 2019-03-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title of the blog')),
                ('pub_date', models.DateField()),
                ('body', models.CharField(max_length=550)),
                ('blogimage', models.ImageField(upload_to='blogimage/')),
            ],
        ),
    ]
